### ISSUE TITLE
Lead users to get access keys from sorna cloud during installation

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-integration-jupyter#3]
* Lead users to get access keys from sorna cloud during installation
 * If no api key is set, notify / lead users to get keys from the site. (when installing integration)

**Comment by achimnol** [comment]
On macOS Sierra 10.12.5, it says (though the webbrowser opens the given site well):
```
You can get your own API keypair from https://cloud.sorna.io. Do you want to open the site? [y/n] y
0:38: execution error: "https://cloud.sorna.io"이(가) ‘open location’ 메시지를 인식하지 못합니다. (-1708)
```
but this is a bug in Apple:
http://bugs.python.org/issue30392

Just ignoring this.

cf)
```
>>> import antigravity
0:37: execution error: "https://xkcd.com/353/"이(가) ‘open location’ 메시지를 인식하지 못합니다. (-1708)
```
